DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION

if VERSION[0:2] > (1, 3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url


from .views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$', get_ueditor_controller)
)

blog/urls.py
from django.conf.urls import *
from blog.views import archive
 
urlpatterns = patterns('',
                      url(r'^$',archive),
                      url(r'^comments/', include('django_comments.urls')),
                      )

blogsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from DjangoUeditor import urls as DjangoUeditor_urls
from django_comments import urls as Comment_urls

urlpatterns = [
    url(r'^', include('blog.urls')),
    url(r'^index/', 'blog.views.index'),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^about/', 'blog.views.about'),
    url(r'^ueditor/', include(DjangoUeditor_urls)),
    url(r'^category/(?P<category_addr>[^/]+)/$', 'blog.views.category', name='category'),
    url(r'^post/(?P<post_addr>[^/]+)/$', 'blog.views.post', name='post'),
    url(r'^comments/', include(Comment_urls)),
    url(r'^ludan/', 'blog.views.ludan'),
    url(r'^oreilly/', 'blog.views.orgen')
]

# use Django server /media/ files
from django.conf import settings
 
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from DjangoUeditor.models import UEditorField
 
# Create your models here.
class BlogCategory(models.Model):
    name = models.CharField(max_length = 20)
    addr = models.CharField(max_length = 256, db_index = True, default='')
    intro = models.TextField
    article_num = models.IntegerField(default = 0)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['name'] 

class BlogPost(models.Model):
    title = models.CharField(max_length = 150)
    addr = models.CharField(max_length = 256, db_index = True, default='')
    author = models.CharField(max_length=128, default='Aleko')
    category = models.ManyToManyField(BlogCategory)
    create_date = models.DateTimeField(auto_now_add=False)
    modify_date = models.DateTimeField(auto_now=False)
    summary = UEditorField('Summary', height=100, width=300,
        default=u'', blank=True, imagePath="uploads/images/",
        toolbars='mini', filePath='uploads/files/', videoPath='uploads/videos/')
    body = UEditorField('Content', height=300, width=1000,
        default=u'', blank=True, imagePath="uploads/images/",
        toolbars='full', filePath='uploads/files/', videoPath='uploads/videos/')
    hit = models.IntegerField(default = 0) 
    like = models.IntegerField(default = 0)
    dislike = models.IntegerField(default = 0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ['-modify_date']

class BlogPostAdmin(admin.ModelAdmin):
    list_display = ('title', 'addr', 'author', 'create_date', 'modify_date')
    class Meta:
        ordering = ['-addr']

class BlogCategoryAdmin(admin.ModelAdmin):
    list_display = ('name', 'addr')

admin.site.register(BlogPost,BlogPostAdmin)
admin.site.register(BlogCategory,BlogCategoryAdmin)

blog/views.py
from django.shortcuts import render
from django.template import loader,Context
from django.http import HttpResponse
from blog.models import BlogPost, BlogCategory
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
# Create your views here.
 
def archive(request):
    posts = BlogPost.objects.all()
    categories = BlogCategory.objects.all()
    t = loader.get_template("archive.html")
    c = Context({'categories':categories, 'posts':posts})
    return HttpResponse(t.render(c))

def about(request):
    categories = BlogCategory.objects.all()
    return render(request, 'about.html', {'categories':categories})

def post(request, post_addr):
    post = BlogPost.objects.get(addr = post_addr)
    categories = BlogCategory.objects.all()
    post.hit += 1
    if 'like' in request.POST:
        post.like += 1
    if 'dislike' in request.POST:
        post.dislike += 1
    post.save()
    return render(request, 'post.html', {'post': post, 'categories':categories})

def category(request, category_addr):
    category = BlogCategory.objects.get(addr = category_addr)
    categories = BlogCategory.objects.all()
    return render(request, 'category.html', { 'category': category, 'categories':categories})

def ludan(request):
    return render(request, 'ludan.html')

def index(request):
    return render(request, 'index.html')

def orgen(request):
    return render(request, 'or-gen.html')

blog/templates/about.html
{% extends "base.html" %}
  {% load comments %}
  {% load staticfiles %}
  {% block css %}
  <link rel="stylesheet" href="{% static "./blog/comment.css" %}">
  <style type="text/css">#intro{font-size: 22px;}</style>
  {% endblock css %}
  {% block title %}About{% endblock title %}
  {% block content %}
  <div class="left">
		<p>&nbsp;</p>	
		<img src="{% static "./blog/aleko.jpg" %}" alt="" width="60%">
		<p id="intro"><b>编程·外语·吉他·方言</b></p>
		<p id="intro">更多有关个人信息欢迎访问 <a class="link" href="https://zh.wikipedia.org/wiki/User:Este_Momento">我的维基百科主页</a></p>
		<p id="intro">联系站长：</p>
    <code>WVd4bGFtRnVaSEp2YkdGMVFHMXpiaTVqYmc9PQ==</code>
		<p id="intro">本网页在 Python 3.4.3 + Django 1.9.4 基础上搭建而成</p>
	</div>
  {% endblock %}

blog/templates/archive.html
{% extends "base.html" %}
{% block content %}
<div class="left" >
  {% for post in posts %}
  <div class="post">
    <h2><a href="/post/{{post.addr}}">{{  post.title }}</a></h2>
    <p class="timestamp">{{  post.author }}, {{ post.create_date | date:"Y/m/d"}}</p>
    <p class="timestamp">编辑： {{ post.modify_date | date:"Y/m/d H:i"}} </p>

    <div class=""><p class="context">{{ post.summary|safe }}</p></div>
    <form class="info" method="post">{% csrf_token %} 浏览：{{ post.hit }}  <input type="submit" id="like" name='like' value="赞（{{ post.like }}）"><input type="submit" id="dislike" name='dislike' value="踩（{{ post.dislike }}）"></form>
  </div>
  {% endfor %}
</div>

{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?8e325c0380e5efc8461d685452382b1c";
            var s = document.getElementsByTagName("script")[0]; 
            s.parentNode.insertBefore(hm, s);
        })();
    </script>

    <title>{% block title %}Blog{% endblock title %} - Where is Aleko?</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static "./blog/syntax/scripts/shCore.js" %}"></script>
    <script type="text/javascript" src="{% static "./blog/syntax/scripts/shBrushBash.js"%}"></script>
    <script type="text/javascript" src="{% static "./blog/syntax/scripts/shBrushPython.js"%}"></script>
    <link type="text/css" rel="stylesheet" href="{% static "./blog/syntax/styles/shCoreEclipse.css"%}"/>
    <script type="text/javascript">SyntaxHighlighter.all();</script>
    <script type="text/javascript">SyntaxHighlighter.defaults['toolbar'] = false;</script>
    <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "./blog/bootstrap-responsive.min.css"%}" rel="stylesheet">
    <script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "./blog/mobile.css" %}" media="screen and (max-width:979px)">
    <link rel="stylesheet" href="{% static "./blog/aleko.css" %}" media="screen and (min-width:980px)">
    <link rel="shortcut icon" href="{% static "./blog/favicon.ico" %}">
    <script type="text/javascript" src="{% static "./blog/syntax/scripts/shCore.js" %}"></script>
    <script type="text/javascript" src="{% static "./blog/syntax/scripts/shBrushBash.js"%}"></script>
    <script type="text/javascript" src="{% static "./blog/syntax/scripts/shBrushPython.js"%}"></script>
    <link type="text/css" rel="stylesheet" href="{% static "./blog/syntax/styles/shCoreEclipse.css"%}"/>
    <script type="text/javascript">SyntaxHighlighter.all();</script>
    <script type="text/javascript">SyntaxHighlighter.defaults['toolbar'] = false;</script>
</head>

<body>
    <nav class="mobile navbar visible-mobile hidden-tablet" role="navigation">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><img src="/static/blog/menu_call.png" alt="nav" width="100%"></button> 
            <div class="nav-brand"><h3><a href="http://www.alekolau.cn">Where is Aleko?</a></h3></div>
          </div>

          <div class="collapse navbar-collapse navlink">    
            <ul class="nav navbar-nav">
                <li class="active"><a href="/index">His life?</a></li>
                <li><a href="/blog">His blog?</a></li>
                <li><a href="/about">Who is he?</a></li>
            </ul>
        </div>
    </nav>
    <nav class="tablet navbar visible-tablet hidden-mobile" role="navigation">
        <div class="nav-brand"><h3><a href="http://www.alekolau.cn">Where is Aleko?</a></h3></div>
        <div class="navlink">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/index">His life?</a></li>
                <li><a href="/blog">His blog?</a></li>
                <li><a href="/about">Who is he?</a></li>
            </ul>
        </div>
    </nav>
    <nav class="desktop navbar visible-desktop" role="navigation">
        <div class="nav-brand"><h1><a href="http://www.alekolau.cn">Where is Aleko?</a></h1></div>
        <div class="navlink">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/index">His life?</a></li>
                <li><a href="/blog">His blog?</a></li>
                <li><a href="/about">Who is he?</a></li>
            </ul>
        </div>
    </nav>
    {% block css %}
    {% endblock css %}
    {% block content %}
    {% endblock content %}
    <div class="right">
        <div class="category">
            <h2> 目录 </h2>
            {% for category in categories %}
            <a href="/category/{{category.addr}}" class="categories">{{ category.name }}</a>
            {% endfor %}
        </div>
        <br>
        <div class="musicbox">
            <h2> 音乐 </h2>
            <script type="text/javascript" language="javascript">
                function iFrameHeight() {
                    var ifm= document.getElementById("mplayer");
                    var subWeb = document.frames ? document.frames["mplayer"].document :
                    ifm.contentDocument;
                    if(ifm != null && subWeb != null) {
                        ifm.height = subWeb.body.scrollHeight;
                    }
                }
            </script>
            <iframe id="mplayer" name="mplayer" frameborder="no" border="0" marginwidth="0" marginheight="0" height="450px" src="http://music.163.com/outchain/player?type=0&id=35601506&auto=0&height=430" onload="iFrameHeight()"></iframe>
        </div>
        <div class="extlink">
            <h2> 友情链接 </h2>
            <a class="link" href="http://blog.wangziq.in/">子勤的小天地</a>
            <a class="link" href="http://www.armyja.cn/">艾米杰的博客</a>
        </div>
    </div>
    <div class="footer" align="center">
        <p class="timestamp">Copyright 2016 Aleko Lau, All Rights Reserved.</p>
        <a class="footfont" href="/admin" width="200px">Admin</a>
        <a href="http://www.miitbeian.gov.cn/" class="footfont">粤ICP备16027334号</a>
    </div>

</body>
</html>

blog/templates/category.html
{% extends "base.html" %}
{% block title %}{{ category.name }}{% endblock title %}
{% block content %}
<div class="left">
  {% for post in category.blogpost_set.all %}
  <div class="post">
    <h2><a href="/post/{{post.addr}}">{{  post.title }}</a></h2>
    <p class="timestamp">By {{  post.author }} at {{ post.create_date | date:"F jS, Y - H:i"}}</p>
    <p class="timestamp">Modified : {{ post.modify_date | date:"F jS, Y - H:i"}} </p>

    <div class="visible-desktop"><p class="context">{{ post.body|safe }}</p></div>
  </div>
  {% endfor %}
</div>
{% endblock %}

blog/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script>
		var _hmt = _hmt || [];
		(function() {
			var hm = document.createElement("script");
			hm.src = "//hm.baidu.com/hm.js?8e325c0380e5efc8461d685452382b1c";
			var s = document.getElementsByTagName("script")[0]; 
			s.parentNode.insertBefore(hm, s);
		})();
	</script>

	<title>Home - Where is Aleko?</title>
	{% load staticfiles %}
	<link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>
	<script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<link href="{% static "./blog/bootstrap-responsive.min.css"%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "./blog/mobile.css" %}" media="screen and (max-width:979px)">
    <link rel="stylesheet" href="{% static "./blog/aleko.css" %}" media="screen and (min-width:980px)">
	<link rel="stylesheet" href="{% static "./blog/index.css" %}">
	<link rel="shortcut icon" href="{% static "./blog/favicon.ico" %}">
</head>

<body>
    <nav class="mobile navbar visible-mobile hidden-tablet" role="navigation">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><img src="/static/blog/menu_call.png" alt="nav" width="100%"></button> 
            <div class="nav-brand"><h3><a href="http://www.alekolau.cn">Where is Aleko?</a></h3></div>
          </div>

          <div class="collapse navbar-collapse navlink">    
            <ul class="nav navbar-nav">
                <li class="active"><a href="/index">His life?</a></li>
                <li><a href="/blog">His blog?</a></li>
                <li><a href="/about">Who is he?</a></li>
            </ul>
        </div>
    </nav>
    <nav class="tablet navbar visible-tablet hidden-mobile" role="navigation">
        <div class="nav-brand"><h3><a href="http://www.alekolau.cn">Where is Aleko?</a></h3></div>
        <div class="navlink">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/index">His life?</a></li>
                <li><a href="/blog">His blog?</a></li>
                <li><a href="/about">Who is he?</a></li>
            </ul>
        </div>
    </nav>
    <nav class="desktop navbar visible-desktop" role="navigation">
        <div class="nav-brand"><h1><a href="http://www.alekolau.cn">Where is Aleko?</a></h1></div>
        <div class="navlink">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/index">His life?</a></li>
                <li><a href="/blog">His blog?</a></li>
                <li><a href="/about">Who is he?</a></li>
            </ul>
        </div>
    </nav>
	<div class="indexwrapper">
		<div class="lt"><img src="{% static "./blog/code0.jpg" %}"  onmouseover="this.src='{% static "./blog/code1.jpg" %}'" onmouseout="this.src='{% static "./blog/code0.jpg" %}'"></div>
		<div class="rt"><img src="{% static "./blog/guitar0.jpg" %}"  onmouseover="this.src='{% static "./blog/guitar1.jpg" %}'" onmouseout="this.src='{% static "./blog/guitar0.jpg" %}'"></div>
		<div class="lb"><img src="{% static "./blog/phonetic0.jpg" %}"  onmouseover="this.src='{% static "./blog/phonetic1.jpg" %}'" onmouseout="this.src='{% static "./blog/phonetic0.jpg" %}'"></div>
		<div class="rb"><img src="{% static "./blog/stamp0.jpg" %}"  onmouseover="this.src='{% static "./blog/stamp1.jpg" %}'" onmouseout="this.src='{% static "./blog/stamp0.jpg" %}'"></div>
	</div>
	<div class="footer" align="center">
		<p class="timestamp">Copyright 2016 Aleko Lau, All Rights Reserved.</p>
		<a class="footfont" href="/admin" width="200px">Admin</a>
		<a href="http://www.miitbeian.gov.cn/" class="footfont">粤ICP备16027334号</a>
	</div>

</body>
</html>

blog/templates/ludan.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>My Love</title>
	<style type="text/css">
		.exp
		{
			margin: auto;
			float: left;
			font: 25px KaiTi,sans-serif;
		}
	</style>
	<link rel="shortcut icon" href="{% static "./blog/favicon.ico" %}">
</head>
<body>
	<img src="{% static "./blog/ludan.jpg" %}" height="512px" width="384px">
	<div class="exp">
		<p>这个偏僻的角落 没什么人找得到</p>
		<p>相信你也不会找到</p>
		<p>相遇 相识 相知</p>
		<p>你带给我许多欢乐 也让我辗转反侧</p>
		<p>直到遇见你 我才真正懂得 什么是爱</p>
		<p>我不善言辞 只会说一句</p>
		<p><b>Te Amo!</b></p>
		<p>&nbsp;</p>
		<p>For 卤蛋</p>
	</div>
</body>
</html>

blog/templates/or-gen.html
<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load staticfiles %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>O'Reilly 封面生成器</title>
    <meta name="viewport" content="width=device-width">

 
    <link href="{% static "./or-gen/css"%}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "./or-gen/master.css"%}">

    <script async="" src="{% static "./or-gen/analytics.js"%}"></script><script src="{% static "./or-gen/jquery-1.9.0.min.js"%}"></script>
    <script src="{% static "./or-gen/jquery.mousewheel.js"%}"></script>
    <script src="{% static "./or-gen/jquery-ui.min.js"%}"></script>
    <script src="{% static "./or-gen/jquery.ui.touch-punch.js"%}"></script>
    <script src="{% static "./or-gen/master.js"%}"></script>
    <script src="{% static "./or-gen/capture.js"%}"></script>
  </head>
<body style="zoom: 1; overflow: auto; cursor: auto;">

<canvas id="book_image" width="516" height="660"></canvas>
<div id="generator" class="contents_cover">
  <div id="book_cover">
    <div id="book_head" class="theme_3">
      <p id="subtitle_en" contenteditable="true">O<span id="apostrophe" class="theme_3">'</span>Reilly 权威参考书籍</p>
      <p id="ribbon" class="hidden" contenteditable="true" style="display: hidden;">第6版</p>
    </div>
    <div id="book_body">
      <p id="subtitle_ja_above" contenteditable="true">
      </p><div id="book_title_cover" class="theme_3">
        <p id="book_title_above" contenteditable="true">从入门到完全放弃</p>
        <p id="book_title_below" contenteditable="true">Apache + PHP</p>
      </div>
      <p id="subtitle_ja_below" contenteditable="true">告诉你史上最差的网页开发后台组合</p>
    </div>
    <div id="animal" class="animal_7" data-animal-index="7" style="left: 252px; top: 228px;"></div>
    <div id="book_foot">
      <div id="foot_left">
        <p id="logo_en" contenteditable="true">O'REILLY</p>
        <p id="logo_ja" contenteditable="true">人民邮电出版社</p>
      </div>
      <div id="foot_right">
        <p id="author" contenteditable="true">Too Young</p>
        <p id="translator" contenteditable="true">涂森魄</p>
      </div>
    </div>
  </div>
  <div id="nav_cover">
    <div id="theme_box">
      <p id="ribbon_half" class="" style="display: block;"></p>
      <p class="box_title">选择书籍主题</p>
      <ul>
        <li class="Web_design_and_authoring" title="Web 设计与制作">Web Design &amp; Authoring
        </li><li class="power_user_computing" title="高级用户计算">Power User Computing
        </li><li class="in_a_nutshell_and_desktop_references" title="“简约不简单”及桌面参考">In a NutShell &amp; Desktop References
        </li><li class="java" title="Java">Java
        </li><li class="linux" title="Linux">Linux
        </li><li class="macintosh" title="Mac">Macintosh
        </li><li class="oracle" title="Oracle">Oracle
        </li><li class="perl" title="Perl">Perl
        </li><li class="security" title="安全">Security
        </li><li class="system_and_network_administration" title="系统与网络管理">System &amp; Network Administration
        </li><li class="unix_c_programming" title="UNIX/C 编程">UNIX/C Programming
        </li><li class="unix_text_procsseing" title="UNIX 文本处理">UNIX Text Processing
        </li><li class="the_web" title="Web">The Web
        </li><li class="windows_programming" title="Windows 编程">Windows Programming
        </li><li class="windows_nt_system_administration" title="Windows NT 系统管理">Windows NT System Administration
        </li><li class="xml" title="XML">XML
        </li><li class="mobile" title="移动端">Mobile
      </li></ul>
    </div>
    <div id="animal_box">
      <p class="box_title">选择动植物图案</p>
      <ul>
        <li class="animal_1" title="灰熊">Grizzly Bear
        </li><li class="animal_2" title="猫">Cat
        </li><li class="animal_3" title="狼">Coyote
        </li><li class="animal_4" title="奶牛">Cow
        </li><li class="animal_5" title="马">Horse
        </li><li class="animal_6" title="鹿">Deer
        </li><li class="animal_7" title="狒狒">Baboon
        </li><li class="animal_8" title="袋熊">Wombat
        </li><li class="animal_9" title="鸭嘴兽">Duckbill
        </li><li class="animal_10" title="蝙蝠">Bat
        </li><li class="animal_11" title="鹈鹕">Pelican
        </li><li class="animal_12" title="鲸头鹳">Shoebill
        </li><li class="animal_13" title="乌鸦">Raven
        </li><li class="animal_14" title="弯嘴鸻">Wrybill
        </li><li class="animal_15" title="鸵鸟">Ostrich
        </li><li class="animal_16" title="变色龙">Chameleon
        </li><li class="animal_17" title="青蛙">Rrog
        </li><li class="animal_18" title="蝾螈">Axolotl
        </li><li class="animal_19" title="蛇">Snake
        </li><li class="animal_20" title="豹纹壁虎">Leopard Gecko
        </li><li class="animal_21" title="鲇">Silurus
        </li><li class="animal_22" title="海鲂">John Dory
        </li><li class="animal_23" title="裸躄鱼">Histrio
        </li><li class="animal_24" title="七鳃鳗">Lamprey
        </li><li class="animal_25" title="翻车鱼">Sunfish
        </li><li class="animal_26" title="蝴蝶">Butterfly
        </li><li class="animal_27" title="蛾">Moth
        </li><li class="animal_28" title="跳蚤">Dragonfly
        </li><li class="animal_29" title="蜻蜓">Flea
        </li><li class="animal_30" title="椿象">Stinkbug
        </li><li class="animal_31" title="蜘蛛">Spider
        </li><li class="animal_32" title="蝎子">Scorpion
        </li><li class="animal_33" title="蟹">Crab
        </li><li class="animal_34" title="龙虾">Lobster
        </li><li class="animal_35" title="鲎">Horseshoe Crab
        </li><li class="animal_36" title="海参">Sea Cucumber
        </li><li class="animal_37" title="鲍鱼">Earshell
        </li><li class="animal_38" title="水母">Jellyfish
        </li><li class="animal_39" title="蝾螺">Astraea
        </li><li class="animal_40" title="蘑菇">Mushroom
      </li></ul>
    </div>
    
  </div>
  <form action="http://oreilly-generator.com/" method="post" name="captureForm" id="captureForm">
    <input name="_qf__captureForm" type="hidden" value="">
<input name="_token" type="hidden" value="fe5879b319a9107d29685e11981e79d3145dd7a0">
<input name="image" type="hidden" value="">
<input name="title" type="hidden" value="">
<input name="author" type="hidden" value="">
<input name="translator" type="hidden" value="">

  </form>
  <!--#box_cover -->
</div>
</body></html>

blog/templates/post.html
{% extends "base.html" %}
  {% load comments %}
  {% load staticfiles %}
  {% block css %}<link rel="stylesheet" href="{% static "./blog/comment.css" %}">{% endblock css %}
  {% block title %}{{ post.title }}{% endblock title %}
  {% block content %}
  <div class="left">
  <h2>{{ post.title }}</h2>
  <p class="timestamp">{{  post.author }}, {{ post.create_date | date:"Y/m/d"}}</p>
  <p class="timestamp">编辑：{{ post.modify_date | date:"Y/m/d H:i"}} </p>

  <p class="context">{{ post.body|safe }}</p>
  <form class="info" method="post">{% csrf_token %} 浏览：{{ post.hit }}  <input type="submit" id="like" name='like' value="赞（{{ post.like }}）"><input type="submit" id="dislike" name='dislike' value="踩（{{ post.dislike }}）"></form>
    <div id="comment">
    <h2>评论：</h2>
    {% render_comment_list for post %}
    <h2>发表评论：</h2>
    {% render_comment_form for post %}
    </div>
  </div>
  {% endblock %}